global_dynamic_buffer:
  buffer_duration_minutes: 5
  buffer_interval_minutes: 5
template_buffers:
  day_template_default_buffer_minutes: 5
  microroutine_buffer_minutes: 5
  routine_buffer_minutes: 5
  subroutine_buffer_minutes: 5
