export default [
  {"id": "Q1", "text": "Worry about things.", "trait": "Neuroticism", "facet": "N1 Anxiety", "key": 1},
  {"id": "Q2", "text": "Make friends easily.", "trait": "Extraversion", "facet": "E1 Friendliness", "key": 1},
  {"id": "Q3", "text": "Have a vivid imagination.", "trait": "Openness", "facet": "O1 Imagination", "key": 1},
  {"id": "Q4", "text": "Trust others.", "trait": "Agreeableness", "facet": "A1 Trust", "key": 1},
  {"id": "Q5", "text": "Complete tasks successfully.", "trait": "Conscientiousness", "facet": "C1 Self-efficacy", "key": 1},
  {"id": "Q6", "text": "Get angry easily.", "trait": "Neuroticism", "facet": "N2 Anger", "key": 1},
  {"id": "Q7", "text": "Love large parties.", "trait": "Extraversion", "facet": "E2 Gregariousness", "key": 1},
  {"id": "Q8", "text": "Believe in the importance of art.", "trait": "Openness", "facet": "O2 Artistic Interests", "key": 1},
  {"id": "Q9", "text": "Use others for my own ends.", "trait": "Agreeableness", "facet": "A2 Morality", "key": -1},
  {"id": "Q10", "text": "Like to tidy up.", "trait": "Conscientiousness", "facet": "C2 Orderliness", "key": 1},
  {"id": "Q11", "text": "Often feel blue.", "trait": "Neuroticism", "facet": "N3 Depression", "key": 1},
  {"id": "Q12", "text": "Take charge.", "trait": "Extraversion", "facet": "E3 Assertiveness", "key": 1},
  {"id": "Q13", "text": "Experience my emotions intensely.", "trait": "Openness", "facet": "O3 Emotionality", "key": 1},
  {"id": "Q14", "text": "Love to help others.", "trait": "Agreeableness", "facet": "A3 Altruism", "key": 1},
  {"id": "Q15", "text": "Keep my promises.", "trait": "Conscientiousness", "facet": "C3 Dutifulness", "key": 1},
  {"id": "Q16", "text": "Find it difficult to approach others.", "trait": "Neuroticism", "facet": "N4 Self-consciousness", "key": 1},
  {"id": "Q17", "text": "Am always busy.", "trait": "Extraversion", "facet": "E4 Activity Level", "key": 1},
  {"id": "Q18", "text": "Prefer variety to routine.", "trait": "Openness", "facet": "O4 Adventurousness", "key": 1},
  {"id": "Q19", "text": "Love a good fight.", "trait": "Agreeableness", "facet": "A4 Cooperation", "key": -1},
  {"id": "Q20", "text": "Work hard.", "trait": "Conscientiousness", "facet": "C4 Achievement-striving", "key": 1},
  {"id": "Q21", "text": "Go on binges.", "trait": "Neuroticism", "facet": "N5 Immoderation", "key": 1},
  {"id": "Q22", "text": "Love excitement.", "trait": "Extraversion", "facet": "E5 Excitement-seeking", "key": 1},
  {"id": "Q23", "text": "Love to read challenging material.", "trait": "Openness", "facet": "O5 Intellect", "key": 1},
  {"id": "Q24", "text": "Believe that I am better than others.", "trait": "Agreeableness", "facet": "A5 Modesty", "key": -1},
  {"id": "Q25", "text": "Am always prepared.", "trait": "Conscientiousness", "facet": "C5 Self-discipline", "key": 1},
  {"id": "Q26", "text": "Panic easily.", "trait": "Neuroticism", "facet": "N6 Vulnerability", "key": 1},
  {"id": "Q27", "text": "Radiate joy.", "trait": "Extraversion", "facet": "E6 Cheerfulness", "key": 1},
  {"id": "Q28", "text": "Tend to vote for liberal political candidates.", "trait": "Openness", "facet": "O6 Liberalism", "key": 1},
  {"id": "Q29", "text": "Sympathize with the homeless.", "trait": "Agreeableness", "facet": "A6 Sympathy", "key": 1},
  {"id": "Q30", "text": "Jump into things without thinking.", "trait": "Conscientiousness", "facet": "C6 Cautiousness", "key": -1},
  {"id": "Q31", "text": "Fear for the worst.", "trait": "Neuroticism", "facet": "N1 Anxiety", "key": 1},
  {"id": "Q32", "text": "Feel comfortable around other people.", "trait": "Extraversion", "facet": "E1 Friendliness", "key": 1},
  {"id": "Q33", "text": "Enjoy wild flights of fancy.", "trait": "Openness", "facet": "O1 Imagination", "key": 1},
  {"id": "Q34", "text": "Believe that others have good intentions.", "trait": "Agreeableness", "facet": "A1 Trust", "key": 1},
  {"id": "Q35", "text": "Excel in what I do.", "trait": "Conscientiousness", "facet": "C1 Self-efficacy", "key": 1},
  {"id": "Q36", "text": "Get irritated easily.", "trait": "Neuroticism", "facet": "N2 Anger", "key": 1},
  {"id": "Q37", "text": "Talk to a lot of different people at parties.", "trait": "Extraversion", "facet": "E2 Gregariousness", "key": 1},
  {"id": "Q38", "text": "See beauty in things that others might not notice.", "trait": "Openness", "facet": "O2 Artistic Interests", "key": 1},
  {"id": "Q39", "text": "Cheat to get ahead.", "trait": "Agreeableness", "facet": "A2 Morality", "key": -1},
  {"id": "Q40", "text": "Often forget to put things back in their proper place.", "trait": "Conscientiousness", "facet": "C2 Orderliness", "key": -1},
  {"id": "Q41", "text": "Dislike myself.", "trait": "Neuroticism", "facet": "N3 Depression", "key": 1},
  {"id": "Q42", "text": "Try to lead others.", "trait": "Extraversion", "facet": "E3 Assertiveness", "key": 1},
  {"id": "Q43", "text": "Feel others' emotions.", "trait": "Openness", "facet": "O3 Emotionality", "key": 1},
  {"id": "Q44", "text": "Am concerned about others.", "trait": "Agreeableness", "facet": "A3 Altruism", "key": 1},
  {"id": "Q45", "text": "Tell the truth.", "trait": "Conscientiousness", "facet": "C3 Dutifulness", "key": 1},
  {"id": "Q46", "text": "Am afraid to draw attention to myself.", "trait": "Neuroticism", "facet": "N4 Self-consciousness", "key": 1},
  {"id": "Q47", "text": "Am always on the go.", "trait": "Extraversion", "facet": "E4 Activity Level", "key": 1},
  {"id": "Q48", "text": "Prefer to stick with things that I know.", "trait": "Openness", "facet": "O4 Adventurousness", "key": -1},
  {"id": "Q49", "text": "Yell at people.", "trait": "Agreeableness", "facet": "A4 Cooperation", "key": -1},
  {"id": "Q50", "text": "Do more than what's expected of me.", "trait": "Conscientiousness", "facet": "C4 Achievement-striving", "key": 1},
  {"id": "Q51", "text": "Rarely overindulge.", "trait": "Neuroticism", "facet": "N5 Immoderation", "key": -1},
  {"id": "Q52", "text": "Seek adventure.", "trait": "Extraversion", "facet": "E5 Excitement-seeking", "key": 1},
  {"id": "Q53", "text": "Avoid philosophical discussions.", "trait": "Openness", "facet": "O5 Intellect", "key": -1},
  {"id": "Q54", "text": "Think highly of myself.", "trait": "Agreeableness", "facet": "A5 Modesty", "key": -1},
  {"id": "Q55", "text": "Carry out my plans.", "trait": "Conscientiousness", "facet": "C5 Self-discipline", "key": 1},
  {"id": "Q56", "text": "Become overwhelmed by events.", "trait": "Neuroticism", "facet": "N6 Vulnerability", "key": 1},
  {"id": "Q57", "text": "Have a lot of fun.", "trait": "Extraversion", "facet": "E6 Cheerfulness", "key": 1},
  {"id": "Q58", "text": "Believe that there is no absolute right or wrong.", "trait": "Openness", "facet": "O6 Liberalism", "key": 1},
  {"id": "Q59", "text": "Feel sympathy for those who are worse off than myself.", "trait": "Agreeableness", "facet": "A6 Sympathy", "key": 1},
  {"id": "Q60", "text": "Make rash decisions.", "trait": "Conscientiousness", "facet": "C6 Cautiousness", "key": -1},
  {"id": "Q61", "text": "Am afraid of many things.", "trait": "Neuroticism", "facet": "N1 Anxiety", "key": 1},
  {"id": "Q62", "text": "Avoid contacts with others.", "trait": "Extraversion", "facet": "E1 Friendliness", "key": -1},
  {"id": "Q63", "text": "Love to daydream.", "trait": "Openness", "facet": "O1 Imagination", "key": 1},
  {"id": "Q64", "text": "Trust what people say.", "trait": "Agreeableness", "facet": "A1 Trust", "key": 1},
  {"id": "Q65", "text": "Handle tasks smoothly.", "trait": "Conscientiousness", "facet": "C1 Self-efficacy", "key": 1},
  {"id": "Q66", "text": "Lose my temper.", "trait": "Neuroticism", "facet": "N2 Anger", "key": 1},
  {"id": "Q67", "text": "Prefer to be alone.", "trait": "Extraversion", "facet": "E2 Gregariousness", "key": -1},
  {"id": "Q68", "text": "Do not like poetry.", "trait": "Openness", "facet": "O2 Artistic Interests", "key": -1},
  {"id": "Q69", "text": "Take advantage of others.", "trait": "Agreeableness", "facet": "A2 Morality", "key": -1},
  {"id": "Q70", "text": "Leave a mess in my room.", "trait": "Conscientiousness", "facet": "C2 Orderliness", "key": -1},
  {"id": "Q71", "text": "Am often down in the dumps.", "trait": "Neuroticism", "facet": "N3 Depression", "key": 1},
  {"id": "Q72", "text": "Take control of things.", "trait": "Extraversion", "facet": "E3 Assertiveness", "key": 1},
  {"id": "Q73", "text": "Rarely notice my emotional reactions.", "trait": "Openness", "facet": "O3 Emotionality", "key": -1},
  {"id": "Q74", "text": "Am indifferent to the feelings of others.", "trait": "Agreeableness", "facet": "A3 Altruism", "key": -1},
  {"id": "Q75", "text": "Break rules.", "trait": "Conscientiousness", "facet": "C3 Dutifulness", "key": -1},
  {"id": "Q76", "text": "Only feel comfortable with friends.", "trait": "Neuroticism", "facet": "N4 Self-consciousness", "key": 1},
  {"id": "Q77", "text": "Do a lot in my spare time.", "trait": "Extraversion", "facet": "E4 Activity Level", "key": 1},
  {"id": "Q78", "text": "Dislike changes.", "trait": "Openness", "facet": "O4 Adventurousness", "key": -1},
  {"id": "Q79", "text": "Insult people.", "trait": "Agreeableness", "facet": "A4 Cooperation", "key": -1},
  {"id": "Q80", "text": "Do just enough work to get by.", "trait": "Conscientiousness", "facet": "C4 Achievement-striving", "key": -1},
  {"id": "Q81", "text": "Easily resist temptations.", "trait": "Neuroticism", "facet": "N5 Immoderation", "key": -1},
  {"id": "Q82", "text": "Enjoy being reckless.", "trait": "Extraversion", "facet": "E5 Excitement-seeking", "key": 1},
  {"id": "Q83", "text": "Have difficulty understanding abstract ideas.", "trait": "Openness", "facet": "O5 Intellect", "key": -1},
  {"id": "Q84", "text": "Have a high opinion of myself.", "trait": "Agreeableness", "facet": "A5 Modesty", "key": -1},
  {"id": "Q85", "text": "Waste my time.", "trait": "Conscientiousness", "facet": "C5 Self-discipline", "key": -1},
  {"id": "Q86", "text": "Feel that I'm unable to deal with things.", "trait": "Neuroticism", "facet": "N6 Vulnerability", "key": 1},
  {"id": "Q87", "text": "Love life.", "trait": "Extraversion", "facet": "E6 Cheerfulness", "key": 1},
  {"id": "Q88", "text": "Tend to vote for conservative political candidates.", "trait": "Openness", "facet": "O6 Liberalism", "key": -1},
  {"id": "Q89", "text": "Am not interested in other people's problems.", "trait": "Agreeableness", "facet": "A6 Sympathy", "key": -1},
  {"id": "Q90", "text": "Rush into things.", "trait": "Conscientiousness", "facet": "C6 Cautiousness", "key": -1},
  {"id": "Q91", "text": "Get stressed out easily.", "trait": "Neuroticism", "facet": "N1 Anxiety", "key": 1},
  {"id": "Q92", "text": "Keep others at a distance.", "trait": "Extraversion", "facet": "E1 Friendliness", "key": -1},
  {"id": "Q93", "text": "Like to get lost in thought.", "trait": "Openness", "facet": "O1 Imagination", "key": 1},
  {"id": "Q94", "text": "Distrust people.", "trait": "Agreeableness", "facet": "A1 Trust", "key": -1},
  {"id": "Q95", "text": "Know how to get things done.", "trait": "Conscientiousness", "facet": "C1 Self-efficacy", "key": 1},
  {"id": "Q96", "text": "Am not easily annoyed.", "trait": "Neuroticism", "facet": "N2 Anger", "key": -1},
  {"id": "Q97", "text": "Avoid crowds.", "trait": "Extraversion", "facet": "E2 Gregariousness", "key": -1},
  {"id": "Q98", "text": "Do not enjoy going to art museums.", "trait": "Openness", "facet": "O2 Artistic Interests", "key": -1},
  {"id": "Q99", "text": "Obstruct others' plans.", "trait": "Agreeableness", "facet": "A2 Morality", "key": -1},
  {"id": "Q100", "text": "Leave my belongings around.", "trait": "Conscientiousness", "facet": "C2 Orderliness", "key": -1},
  {"id": "Q101", "text": "Feel comfortable with myself.", "trait": "Neuroticism", "facet": "N3 Depression", "key": -1},
  {"id": "Q102", "text": "Wait for others to lead the way.", "trait": "Extraversion", "facet": "E3 Assertiveness", "key": -1},
  {"id": "Q103", "text": "Don't understand people who get emotional.", "trait": "Openness", "facet": "O3 Emotionality", "key": -1},
  {"id": "Q104", "text": "Take no time for others.", "trait": "Agreeableness", "facet": "A3 Altruism", "key": -1},
  {"id": "Q105", "text": "Break my promises.", "trait": "Conscientiousness", "facet": "C3 Dutifulness", "key": -1},
  {"id": "Q106", "text": "Am not bothered by difficult social situations.", "trait": "Neuroticism", "facet": "N4 Self-consciousness", "key": -1},
  {"id": "Q107", "text": "Like to take it easy.", "trait": "Extraversion", "facet": "E4 Activity Level", "key": -1},
  {"id": "Q108", "text": "Am attached to conventional ways.", "trait": "Openness", "facet": "O4 Adventurousness", "key": -1},
  {"id": "Q109", "text": "Get back at others.", "trait": "Agreeableness", "facet": "A4 Cooperation", "key": -1},
  {"id": "Q110", "text": "Put little time and effort into my work.", "trait": "Conscientiousness", "facet": "C4 Achievement-striving", "key": -1},
  {"id": "Q111", "text": "Am able to control my cravings.", "trait": "Neuroticism", "facet": "N5 Immoderation", "key": -1},
  {"id": "Q112", "text": "Act wild and crazy.", "trait": "Extraversion", "facet": "E5 Excitement-seeking", "key": 1},
  {"id": "Q113", "text": "Am not interested in theoretical discussions.", "trait": "Openness", "facet": "O5 Intellect", "key": -1},
  {"id": "Q114", "text": "Boast about my virtues.", "trait": "Agreeableness", "facet": "A5 Modesty", "key": -1},
  {"id": "Q115", "text": "Have difficulty starting tasks.", "trait": "Conscientiousness", "facet": "C5 Self-discipline", "key": -1},
  {"id": "Q116", "text": "Remain calm under pressure.", "trait": "Neuroticism", "facet": "N6 Vulnerability", "key": -1},
  {"id": "Q117", "text": "Look at the bright side of life.", "trait": "Extraversion", "facet": "E6 Cheerfulness", "key": 1},
  {"id": "Q118", "text": "Believe that we should be tough on crime.", "trait": "Openness", "facet": "O6 Liberalism", "key": -1},
  {"id": "Q119", "text": "Try not to think about the needy.", "trait": "Agreeableness", "facet": "A6 Sympathy", "key": -1},
  {"id": "Q120", "text": "Act without thinking.", "trait": "Conscientiousness", "facet": "C6 Cautiousness", "key": -1},
];
