export default [
  // Extraversion (20-item scale)
  { id: "E1", text: "Am the life of the party.", trait: "Extraversion", key: 1 },
  { id: "E2", text: "Feel comfortable around people.", trait: "Extraversion", key: 1 },
  { id: "E3", text: "Start conversations.", trait: "Extraversion", key: 1 },
  { id: "E4", text: "Talk to a lot of different people at parties.", trait: "Extraversion", key: 1 },
  { id: "E5", text: "Don't mind being the center of attention.", trait: "Extraversion", key: 1 },
  { id: "E6", text: "Make friends easily.", trait: "Extraversion", key: 1 },
  { id: "E7", text: "Take charge.", trait: "Extraversion", key: 1 },
  { id: "E8", text: "Know how to captivate people.", trait: "Extraversion", key: 1 },
  { id: "E9", text: "Feel at ease with people.", trait: "Extraversion", key: 1 },
  { id: "E10", text: "Am skilled in handling social situations.", trait: "Extraversion", key: 1 },
  { id: "E11", text: "Don't talk a lot.", trait: "Extraversion", key: -1 },
  { id: "E12", text: "Keep in the background.", trait: "Extraversion", key: -1 },
  { id: "E13", text: "Have little to say.", trait: "Extraversion", key: -1 },
  { id: "E14", text: "Don't like to draw attention to myself.", trait: "Extraversion", key: -1 },
  { id: "E15", text: "Am quiet around strangers.", trait: "Extraversion", key: -1 },
  { id: "E16", text: "Find it difficult to approach others.", trait: "Extraversion", key: -1 },
  { id: "E17", text: "Often feel uncomfortable around others.", trait: "Extraversion", key: -1 },
  { id: "E18", text: "Bottle up my feelings.", trait: "Extraversion", key: -1 },
  { id: "E19", text: "Am a very private person.", trait: "Extraversion", key: -1 },
  { id: "E20", text: "Wait for others to lead the way.", trait: "Extraversion", key: -1 },

  // Agreeableness (20-item scale)
  { id: "A1", text: "Am interested in people.", trait: "Agreeableness", key: 1 },
  { id: "A2", text: "Sympathize with others' feelings.", trait: "Agreeableness", key: 1 },
  { id: "A3", text: "Have a soft heart.", trait: "Agreeableness", key: 1 },
  { id: "A4", text: "Take time out for others.", trait: "Agreeableness", key: 1 },
  { id: "A5", text: "Feel others' emotions.", trait: "Agreeableness", key: 1 },
  { id: "A6", text: "Make people feel at ease.", trait: "Agreeableness", key: 1 },
  { id: "A7", text: "Inquire about others' well-being.", trait: "Agreeableness", key: 1 },
  { id: "A8", text: "Know how to comfort others.", trait: "Agreeableness", key: 1 },
  { id: "A9", text: "Love children.", trait: "Agreeableness", key: 1 },
  { id: "A10", text: "Am on good terms with nearly everyone.", trait: "Agreeableness", key: 1 },
  { id: "A11", text: "Have a good word for everyone.", trait: "Agreeableness", key: 1 },
  { id: "A12", text: "Show my gratitude.", trait: "Agreeableness", key: 1 },
  { id: "A13", text: "Think of others first.", trait: "Agreeableness", key: 1 },
  { id: "A14", text: "Love to help others.", trait: "Agreeableness", key: 1 },
  { id: "A15", text: "Insult people.", trait: "Agreeableness", key: -1 },
  { id: "A16", text: "Am not interested in other people's problems.", trait: "Agreeableness", key: -1 },
  { id: "A17", text: "Feel little concern for others.", trait: "Agreeableness", key: -1 },
  { id: "A18", text: "Am not really interested in others.", trait: "Agreeableness", key: -1 },
  { id: "A19", text: "Am hard to get to know.", trait: "Agreeableness", key: -1 },
  { id: "A20", text: "Am indifferent to the feelings of others.", trait: "Agreeableness", key: -1 },

  // Conscientiousness (20-item scale)
  { id: "C1", text: "Am always prepared.", trait: "Conscientiousness", key: 1 },
  { id: "C2", text: "Pay attention to details.", trait: "Conscientiousness", key: 1 },
  { id: "C3", text: "Get chores done right away.", trait: "Conscientiousness", key: 1 },
  { id: "C4", text: "Like order.", trait: "Conscientiousness", key: 1 },
  { id: "C5", text: "Follow a schedule.", trait: "Conscientiousness", key: 1 },
  { id: "C6", text: "Am exacting in my work.", trait: "Conscientiousness", key: 1 },
  { id: "C7", text: "Do things according to a plan.", trait: "Conscientiousness", key: 1 },
  { id: "C8", text: "Continue until everything is perfect.", trait: "Conscientiousness", key: 1 },
  { id: "C9", text: "Make plans and stick to them.", trait: "Conscientiousness", key: 1 },
  { id: "C10", text: "Love order and regularity.", trait: "Conscientiousness", key: 1 },
  { id: "C11", text: "Like to tidy up.", trait: "Conscientiousness", key: 1 },
  { id: "C12", text: "Leave my belongings around.", trait: "Conscientiousness", key: -1 },
  { id: "C13", text: "Make a mess of things.", trait: "Conscientiousness", key: -1 },
  { id: "C14", text: "Often forget to put things back in their proper place.", trait: "Conscientiousness", key: -1 },
  { id: "C15", text: "Shirk my duties.", trait: "Conscientiousness", key: -1 },
  { id: "C16", text: "Neglect my duties.", trait: "Conscientiousness", key: -1 },
  { id: "C17", text: "Waste my time.", trait: "Conscientiousness", key: -1 },
  { id: "C18", text: "Do things in a half-way manner.", trait: "Conscientiousness", key: -1 },
  { id: "C19", text: "Find it difficult to get down to work.", trait: "Conscientiousness", key: -1 },
  { id: "C20", text: "Leave a mess in my room.", trait: "Conscientiousness", key: -1 },

  // Emotional Stability (20-item scale)
  { id: "ES1", text: "Am relaxed most of the time.", trait: "Emotional Stability", key: 1 },
  { id: "ES2", text: "Seldom feel blue.", trait: "Emotional Stability", key: 1 },
  { id: "ES3", text: "Am not easily bothered by things.", trait: "Emotional Stability", key: 1 },
  { id: "ES4", text: "Rarely get irritated.", trait: "Emotional Stability", key: 1 },
  { id: "ES5", text: "Seldom get mad.", trait: "Emotional Stability", key: 1 },
  { id: "ES6", text: "Get stressed out easily.", trait: "Emotional Stability", key: -1 },
  { id: "ES7", text: "Worry about things.", trait: "Emotional Stability", key: -1 },
  { id: "ES8", text: "Am easily disturbed.", trait: "Emotional Stability", key: -1 },
  { id: "ES9", text: "Get upset easily.", trait: "Emotional Stability", key: -1 },
  { id: "ES10", text: "Change my mood a lot.", trait: "Emotional Stability", key: -1 },
  { id: "ES11", text: "Have frequent mood swings.", trait: "Emotional Stability", key: -1 },
  { id: "ES12", text: "Get irritated easily.", trait: "Emotional Stability", key: -1 },
  { id: "ES13", text: "Often feel blue.", trait: "Emotional Stability", key: -1 },
  { id: "ES14", text: "Get angry easily.", trait: "Emotional Stability", key: -1 },
  { id: "ES15", text: "Panic easily.", trait: "Emotional Stability", key: -1 },
  { id: "ES16", text: "Feel threatened easily.", trait: "Emotional Stability", key: -1 },
  { id: "ES17", text: "Get overwhelmed by emotions.", trait: "Emotional Stability", key: -1 },
  { id: "ES18", text: "Take offense easily.", trait: "Emotional Stability", key: -1 },
  { id: "ES19", text: "Get caught up in my problems.", trait: "Emotional Stability", key: -1 },
  { id: "ES20", text: "Grumble about things.", trait: "Emotional Stability", key: -1 },

  // Intellect or Imagination (20-item scale)
  { id: "O1", text: "Have a rich vocabulary.", trait: "Intellect/Imagination", key: 1 },
  { id: "O2", text: "Have a vivid imagination.", trait: "Intellect/Imagination", key: 1 },
  { id: "O3", text: "Have excellent ideas.", trait: "Intellect/Imagination", key: 1 },
  { id: "O4", text: "Am quick to understand things.", trait: "Intellect/Imagination", key: 1 },
  { id: "O5", text: "Use difficult words.", trait: "Intellect/Imagination", key: 1 },
  { id: "O6", text: "Spend time reflecting on things.", trait: "Intellect/Imagination", key: 1 },
  { id: "O7", text: "Am full of ideas.", trait: "Intellect/Imagination", key: 1 },
  { id: "O8", text: "Carry the conversation to a higher level.", trait: "Intellect/Imagination", key: 1 },
  { id: "O9", text: "Catch on to things quickly.", trait: "Intellect/Imagination", key: 1 },
  { id: "O10", text: "Can handle a lot of information.", trait: "Intellect/Imagination", key: 1 },
  { id: "O11", text: "Love to think up new ways of doing things.", trait: "Intellect/Imagination", key: 1 },
  { id: "O12", text: "Love to read challenging material.", trait: "Intellect/Imagination", key: 1 },
  { id: "O13", text: "Am good at many things.", trait: "Intellect/Imagination", key: 1 },
  { id: "O14", text: "Have difficulty understanding abstract ideas.", trait: "Intellect/Imagination", key: -1 },
  { id: "O15", text: "Am not interested in abstract ideas.", trait: "Intellect/Imagination", key: -1 },
  { id: "O16", text: "Do not have a good imagination.", trait: "Intellect/Imagination", key: -1 },
  { id: "O17", text: "Try to avoid complex people.", trait: "Intellect/Imagination", key: -1 },
  { id: "O18", text: "Have difficulty imagining things.", trait: "Intellect/Imagination", key: -1 },
  { id: "O19", text: "Avoid difficult reading material.", trait: "Intellect/Imagination", key: -1 },
  { id: "O20", text: "Will not probe deeply into a subject.", trait: "Intellect/Imagination", key: -1 },
];
